{% set name = "napari-seedseg" %}
{% set version = "0.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari_seedseg-{{ version }}.tar.gz
  sha256: df3e58dc5618fbd4bb95da20a48c62b42922a02682c692a33cee5d68e623d5a6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - magicgui
    - napari
    - numpy
    - opencv
    - python >=3.8
    - qtpy
    - scikit-image >=0.19.3

test:
  imports:
    - napari_seedseg
  commands:
    - pip list
    # - pip check  # Fails due to opencv-python-headless
  requires:
    - pip

about:
  home: https://github.com/rezaakb/napari-seedseg
  summary: A simple plugin for segmentation
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
